#!/usr/bin/env bash
# A script that displays "Best School" and "Hi" on the 9th iteration

i=1

while [ $h -le 10 ]
do
    if [ $h -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((i++))
done
